Feature b
maths29/portfolio-worksection pull request #1
Opened 2023-03-29 17:01 UTC by maths29

in this project, i :
Added an index.html file that includes the list my portfolio projects.
- Added a style.css file that includes flexbox and CSS Grid for the parent div.
- Added all the linter files, readme file and a test.Md file that should be ignored by git

2023-03-29 17:23 UTC, Trast00 reviewed
Hi @maths29 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a describetive title, please consider update the title (ex: `Add <FEATURE ADDED>`)  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@Trast00) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-30 08:03 UTC, divinecharlotte requested changes
Hi @maths29    , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 


- Descriptive PR ✔️ 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

_Check the comments under the review._



## Optional suggestions

- [ ] [OPTIONAL] kindly next time make sure to make your commit message more meaningful by putting them in imperative form and making the first letter a capital letter this will make your PR look more professional

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 08:03 UTC, divinecharlotte commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/iwu-john)
- [ ] kindly consider adding a working link to your Linkdhin account to give a good user experience to the people visiting your readme

2023-03-30 08:03 UTC, divinecharlotte commented on style.css
>  }
- [ ] kindly consider alligning The content of the project with  flexbox to make styling more easly when changing to another screen or in case you might need to change it to be more flexible

2023-03-30 08:03 UTC, divinecharlotte commented on style.css
> -
- [ ] kindly consider following  the button styling: Active, Hover and Pressed to give good user experience

2023-03-30 08:03 UTC, divinecharlotte commented on style.css
> -color: #172b4d;
- [ ] kindly consider having a single h1 because it creates hierarchy and gives your page a more logical structure

2023-03-30 08:03 UTC, divinecharlotte commented on style.css
> -font-size: 16px;
- [ ] kindly consider adding this `let's connect` in a h tag to fulfil the below requirement 👇 
- > If there are other titles (e.g., "Let's connect") use a header tag `hx`

2023-03-30 08:03 UTC, divinecharlotte commented on style.css
>  }
1. [ ] i can see you used grid to display the contents good job so far 👍  but kindly consider aligning this with a flex box to fulfil this requirement 👉   "The content is aligned with flexbox"

2023-03-30 08:03 UTC, divinecharlotte commented on style.css
> -}
- [ ] kindly consider sticking to the provided figma design as much as possible in order to have an exact duplicate of the given design as required chechk the images below 👇 
- your design 
<img width="383" alt="Screen Shot 2023-03-30 at 09 52 27" src="https://user-images.githubusercontent.com/60146030/228769190-28e1df58-68d5-4c83-ba74-402e890fbdb5.png">

- provided design 
<img width="377" alt="Screen Shot 2023-03-30 at 09 58 14" src="https://user-images.githubusercontent.com/60146030/228769831-1865a1fc-829a-487f-bd64-ecf4d1d369b0.png">


please put this into consideration the following :
> 1. The section has the margins (top, bottom, left, right) defined in the design
1. The section uses the font and colours (background and font) defined for the template

2023-03-30 12:16 UTC, Felix45 requested changes
Hi @maths29 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966" />

 ## Highlights :heavy_check_mark: 
- [x] No linter errors :white_check_mark: 
- [x] Descriptive pull request title and summary :white_check_mark:  
- [x] Repository has a professional readme file :white_check_mark: 
- [x] Implemented some of the changes from the previous reviewer :white_check_mark:  


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 12:16 UTC, Felix45 commented on style.css
>  }
- [ Required ] As requested by a previous reviewer please consider aligning the contents of the `.cards-work` using flexbox, this is a requirement as stated in the porject requirements. You forgot to include the `display: flex` CSS property which lays out elements using flex box, please refactor this code as shown below.

```CSS
.card-works {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  border: 1px solid #dee1e6;
  border-radius: 16px;
  padding: 20px;
  background-color: white;
}
```

## Project requirements
![Screenshot from 2023-03-30 14-13-59](https://user-images.githubusercontent.com/16392046/228819182-a4b63288-6f7d-4771-ba95-e50844238460.png)

2023-03-30 12:16 UTC, Felix45 commented on index.html
- [ Required ] As requested by a previous reviewer please make sure that your webpage has only one `h1` tag it would be better if  the `h1` tags in the `works section` and `about us section` are changed to an `hx` tag preferably an `h2` tag. These changes will give your webpage a more logical structure that gives the best results when parsed by a search engine.

2023-03-30 12:16 UTC, Felix45 commented on style.css
>  }
- [ Required ] As requested by a previous reviewer please consider laying out the elements in the about section using `flexbox` as stated in the project requirements. Please see the screenshot below for more details on this and rectify this.

## Project requirements
![Screenshot from 2023-03-30 14-33-12](https://user-images.githubusercontent.com/16392046/228824116-8dcf2b38-5b28-4f40-9ca2-254cfa46a3f7.png)

2023-03-30 12:16 UTC, Felix45 commented on style.css
> +}
- [ Optional ] I think it would be better if your design matches the design on the FIgma template provided, this will showcase your skill to bring designs to life as a developer. Currently, the languages section of your design varies significantly from the Figma design, please see the screenshot below and rectify this.
   
    - Differences
      - The images of the programming languages should be colored images
      - The margins between a programming language image and the text should be similar to Figma template
      - The `down` and `right` arrow icons would match the Figma design more if you used an `image` or a `icon library` e.g Fontawsome

## Figma design
![Screenshot from 2023-03-30 14-47-20](https://user-images.githubusercontent.com/16392046/228827135-06b96e33-7fb3-4f27-91b2-8013c41c63b7.png)




## Your design
![Screenshot from 2023-03-30 14-42-46](https://user-images.githubusercontent.com/16392046/228826897-c29f24ba-59dc-4927-81a0-c73ed6377005.png)

2023-03-30 12:16 UTC, Felix45 commented on style.css
> -}
- [ Required ] As requested by a previous reviewer please make sure that the `margins` and `paddings` in your design are consistent with those in the Figma design. At width `375px` i noticed that your webpage has a horizontal scroll which should not be the case. Please see the screenshot below and rectify this.

## Figma design
![Screenshot from 2023-03-30 15-06-03](https://user-images.githubusercontent.com/16392046/228830803-575b9f45-c029-494b-a63d-904835c960d3.png)

## Your design
https://user-images.githubusercontent.com/16392046/228832058-008f03c4-62bb-49de-a991-339ccf3e6055.mp4

2023-03-31 18:46 UTC, RaoAkif approved these changes
## STATUS: APPROVED 🎉🎉🎉

Hi @maths29,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approve-image](https://ci5.googleusercontent.com/proxy/zq80mRZVpq-eAhdzmvNYP-LJmESV4U2mCLkUDj-J77H6FKB6oLO-eL8kGFENlnk15aQQPnJ2K7hSGZiaZBHMKFZEM6yCAT5H0leJxszpiJ_ZRxNc5L9uv6Wf0BFZUomZYiYN6ppiHgltD6qjc_Kh8RbH3b4nVLPghJlpfxM29IAi_q8djloxFmcQQ_I2iIY_rYXVUeBiSfNsVRfk0iq3wo75_nf9QHejNs5EwcDwp7n4vukAV0rFF6xBnAenIBlJ9_CuSGN37pZ0FDROc_LU_rInohwgD5sTJnITUxeXsq5juhu5btEu0AhtqpFV5MDVTQMfZw=s0-d-e1-ft#https://camo.githubusercontent.com/b4e8f035e0f2d20302034402026b8df675e3a9dd93b722d1b0a047112e68044d/68747470733a2f2f632e74656e6f722e636f6d2f4a52665739444c534f764141414141432f7365616c2d7365616c2d6f662d617070726f76616c2e676966)

## Highlights
✔ Linters are on point 
✔ Splendid work with the README file
✔ Great use of GitHub flow
✔ Good code design and implementation

## Optional suggestions
You have done a lot of effort in implementing the comments given by previous reviewer. I have noticed few following things. Kindly implement these.
- The top section of your profile is `work section`. The `landing page` is missing. 
![image](https://user-images.githubusercontent.com/61361037/229203702-f553154c-d995-4652-8df2-f4ad3ff3208d.png)
- Contact form styling can be improved. Please spend some time by comparing your design with FIGMA design. Look, this section is the one, your client are going to approach you. Don't you think, it should be pixel perfect.

| Your Design   | FIGMA Design  |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/61361037/229204364-149d6fb2-0c9b-42d6-8bce-ab8abdeb221a.png)| ![image](https://user-images.githubusercontent.com/61361037/229204308-8d380160-abff-4f90-84cb-d824e65165dd.png)|

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 10:25 UTC, merged